language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test
  - DB_NAME=travis
  - DB_USER=travis
  - DB_PASS=travis
  - DB_PORT=5432
  - DB_HOST=127.0.0.1
  - SECRET_KEY=any_secret

before_script:
  - psql -c "CREATE DATABASE ${DB_NAME};"" -U ${DB_USER}
  - psql -c "CREATE USER ${DB_USER} WITH PASSWORD ${DB_PASS};" -U ${DB_USER}
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate
script:
  - npm test
after_success:
  - npm run coverage